name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Run tests (chromium)
        run: npx playwright test --project=chromium
  test-other-browsers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, webkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Run tests for ${{ matrix.browser }}
        run: npx playwright test --project=${{ matrix.browser }} --grep-invert @lighthouse
